import { Theme } from "../theme.slint";

export component TextInputField inherits Rectangle {
    in property <color> bg: Theme.bg-input;
    in property <length> field-height: 26px;
    in-out property <string> text <=> input.text;
    in property <bool> single-line: true;
    in property <bool> wrap: false;

    callback edited(string);
    callback accepted(string);

    height: field-height;
    background: bg;
    border-radius: Theme.radius-sm;
    clip: true;

    input := TextInput {
        width: 100%;
        height: 100%;
        color: black;
        font-size: 13px;
        single-line: root.single-line;
        wrap: root.wrap ? word-wrap : no-wrap;
        text <=> root.text;
        edited => { root.edited(self.text); }
        accepted => { root.accepted(self.text); }
    }
}
