import { Theme } from "../../theme.slint";

export component CurrencyConfigSection inherits Rectangle {
    width: 100%;
    background: transparent;

    in-out property <string> currency: "₹";

    callback currency-changed();

    VerticalLayout {
        spacing: Theme.pad-md;

        Text {
            text: "Currency";
            color: Theme.accent;
            font-size: 18px;
            horizontal-alignment: left;
        }

        HorizontalLayout {
            spacing: Theme.pad-md;
            Text {
                text: "Symbol:";
                color: Theme.text-primary;
                width: 80px;
                vertical-alignment: center;
            }
            Rectangle {
                width: 80px;
                height: 30px;
                background: Theme.bg-input;
                border-radius: Theme.radius-sm;
                clip: true;
                TextInput {
                    width: 100%;
                    height: 100%;
                    color: black;
                    single-line: true;
                    text <=> root.currency;
                    edited => { root.currency-changed(); }
                }
            }
        }
    }
}
