import { TableArea } from "../db-types.slint";
import { Theme } from "../theme.slint";
import { AreaConfigSection } from "settings/area_config.slint";
import { GstConfigSection } from "settings/gst_config.slint";
import { CurrencyConfigSection } from "settings/currency_config.slint";

export component SettingsView inherits Rectangle {
    width: 100%;
    height: 100%;

    in property <[TableArea]> areas;

    callback reorder-area(int, int);
    callback add-area();
    callback remove-area(int);
    callback update-area-name(int, string);
    callback gst-changed();
    callback currency-changed();

    in-out property <string> cgst-text: "0";
    in-out property <string> sgst-text: "0";
    in-out property <string> currency: "₹";

    VerticalLayout {
        padding: Theme.pad-xl;
        spacing: Theme.pad-xl;

        Text {
            text: "Settings";
            font-size: 24px;
            color: #fafafa;
            horizontal-alignment: center;
        }

        AreaConfigSection {
            areas: root.areas;
            add-area => { root.add-area(); }
            reorder-area(from, to) => { root.reorder-area(from, to); }
            remove-area(index) => { root.remove-area(index); }
            update-area-name(index, name) => {
                root.update-area-name(index, name);
            }
        }

        GstConfigSection {
            cgst-text <=> root.cgst-text;
            sgst-text <=> root.sgst-text;
            gst-changed => { root.gst-changed(); }
        }

        CurrencyConfigSection {
            currency <=> root.currency;
            currency-changed => { root.currency-changed(); }
        }

        Rectangle { vertical-stretch: 1; }
    }
}
