export struct MenuItem {
    id: int,
    name: string,
    code: string,
    price: float,
    category: string,
}

export struct IngredientRow {
    link_id: int,
    ingredient_id: int,
    name: string,
    quantity: float,
    unit: string,
    estimated_cost: float,
}

export struct OrderLine {
    name: string,
    price: float,
    quantity: int,
}

export struct TableArea {
    name: string,
    tables: int,
}
